# Extend regex patterns for secret scanning (used by secret_patterns.py if you want to add)
# Example:
# - label: "Custom API Key"
#   regex: "(?i)mycompany(.{0,10})?api(.{0,3})?key\s*[:=]\s*['\\"A-Za-z0-9_-]{20,}"
